### ISSUE TITLE
Clicking on "rescale" in Blender 4 results in an error, without scaling it to the target height

### ISSUE THREAD

**Issue by OrenjiVR** [triazo/immersive_scaler#20]
When I clock on "Rescale" the "Target Height" is not met and this error will be thrown out.
It seems like the Upper Body Percentage and Custom Arm Ratio does influence the scaling though.

```
Python: Traceback (most recent call last):
  File "F:\SteamLibrary\steamapps\common\Blender\4.0\python\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\immersive_scaler\operations.py", line 58, in temp_ensure_enabled
    yield
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\immersive_scaler\operations.py", line 1133, in execute
    return self.execute_main(context, arm, meshes)
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\immersive_scaler\operations.py", line 1153, in execute_main
    rescale_main(
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\immersive_scaler\operations.py", line 838, in rescale_main
    scale_to_floor(arm_to_legs, arm_thickness, leg_thickness, extra_leg_length, scale_hand, thigh_percentage, custom_scale_ratio, scale_relative, upper_body_percent)
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\immersive_scaler\operations.py", line 719, in scale_to_floor
    apply_pose_to_rest()
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\immersive_scaler\operations.py", line 1102, in apply_pose_to_rest
    bpy.ops.pose.armature_apply({'active_object': arm})
  File "F:\SteamLibrary\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "F:\SteamLibrary\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported


```

**Comment by triazo** [comment]
I ran into this a week or two ago.  It was just one call that hadn't been updated to the new api. Should be fixed in the latest release.

**Comment by OrenjiVR** [comment]
Thanks a lot!
I did not notice a new release. Can confirm it works now.
There just seems to be a tiny mistake in the version number, when installed. Not enough of an issue to make a ticket though.
![image](https://github.com/triazo/immersive_scaler/assets/114165880/20a9d1ab-5b28-49d7-aa65-ac765663e312)
